export const dynamic="force-dynamic";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { CreditPurchaseForm } from "@/components/credit-purchase-form";
function money(v:number|string|null|undefined){return v==null?"—":Number(v).toLocaleString("pt-MZ")+" MZN";}
export default async function CreditosPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
 const params=await searchParams; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)return null;
 const [{data:owned},{data:members},{data:packages}]=await Promise.all([
  supabase.from("businesses").select("id,name").eq("owner_id",user.id).order("name"),supabase.from("business_members").select("business_id").eq("user_id",user.id).in("role",["owner","admin","operator"]),supabase.from("credit_packages").select("id,code,name,credit_volume,price_mzn,active").eq("active",true).order("credit_volume")]);
 const ids=[...new Set((members??[]).map(x=>x.business_id))]; const {data:managed}=ids.length?await supabase.from("businesses").select("id,name").in("id",ids).order("name"):{data:[] as {id:string;name:string}[]};
 const businesses=[...(owned??[]),...(managed??[]).filter(b=>!(owned??[]).some(o=>o.id===b.id))];
 const {data:wallets}=businesses.length?await supabase.from("business_credit_wallets").select("id,business_id,balance_credits").in("business_id",businesses.map(b=>b.id)):{data:[] as {id:string;business_id:string;balance_credits:number}[]};
 const walletMap=new Map((wallets??[]).map(w=>[w.business_id,w.balance_credits])); const walletIds=(wallets??[]).map(w=>w.id);
 const {data:transactions}=walletIds.length?await supabase.from("credit_transactions").select("id,wallet_id,type,credits,amount_mzn,description,created_at").in("wallet_id",walletIds).order("created_at",{ascending:false}).limit(20):{data:[] as {id:string;wallet_id:string;type:string;credits:number;amount_mzn:number|null;description:string|null;created_at:string}[]};
 const {data:purchaseRequests}=businesses.length?await supabase.from("credit_purchase_requests").select("id,business_id,credits,amount_mzn,payment_method,status,created_at").in("business_id",businesses.map(b=>b.id)).order("created_at",{ascending:false}).limit(8):{data:[]};
 const flash=params.success==="purchase"?"Pedido de compra registado.":params.error==="purchase"?"Não foi possível registar o pedido de compra.":"";
 return <main className="dashboard-main"><div className="dashboard-content">{flash&&<div className="account-success" style={{marginBottom:16}}>{flash}</div>}
 <header className="dashboard-topbar"><div><span className="dashboard-kicker">Conta · Créditos</span><h1>Créditos</h1><p>Um recurso transversal do MozEmpresas. Use créditos em funcionalidades elegíveis, incluindo publicidade.</p></div><Link className="btn" href="/dashboard/publicidade">Ir para Publicidade →</Link></header>
 <section className="dashboard-section" style={{marginTop:18}}><div className="dashboard-section-head"><div><span className="dashboard-kicker">Saldos</span><h2>Contas de créditos</h2><p className="muted">Cada empresa tem o seu próprio saldo.</p></div></div>{businesses.length?<div className="grid" style={{gridTemplateColumns:"repeat(3,minmax(0,1fr))"}}>{businesses.map(b=><div className="card" key={b.id}><span className="dashboard-kicker">{b.name}</span><h2 style={{margin:"6px 0"}}>{(walletMap.get(b.id)??0).toLocaleString("pt-MZ")} cr</h2><p className="muted">Saldo disponível</p></div>)}</div>:<div className="card"><strong>Associe uma empresa primeiro.</strong><p className="muted">É necessário representar uma empresa para comprar créditos.</p><Link className="btn primary" href="/dashboard/empresas">Gerir empresa →</Link></div>}</section>
 <section className="dashboard-section" style={{marginTop:18}}><div className="dashboard-section-head"><div><span className="dashboard-kicker">Comprar créditos</span><h2>Escolha um pacote</h2><p className="muted">Os pacotes agora são seleccionáveis e o pedido começa nesta página.</p></div></div>{businesses.length?<CreditPurchaseForm businesses={businesses} packages={packages??[]}/>:null}</section>
 <section className="dashboard-section" style={{marginTop:18}}><div className="dashboard-section-head"><div><span className="dashboard-kicker">Pedidos</span><h2>Compras recentes</h2></div></div>{(purchaseRequests??[]).length?(purchaseRequests??[]).map((r:{id:string;business_id:string;credits:number;amount_mzn:number;payment_method:string|null;status:string;created_at:string})=><div key={r.id} className="credit-request-row"><div><strong>{businesses.find(b=>b.id===r.business_id)?.name||"Empresa"} · {r.credits.toLocaleString("pt-MZ")} créditos</strong><small>{money(r.amount_mzn)} · {r.payment_method||"Pagamento"} · {new Date(r.created_at).toLocaleString("pt-MZ")}</small></div><span>{r.status}</span></div>):<p className="muted">Ainda não existem pedidos de compra.</p>}</section>
 <section className="dashboard-section" style={{marginTop:18}}><div className="dashboard-section-head"><div><span className="dashboard-kicker">Histórico</span><h2>Movimentos recentes</h2></div></div>{(transactions??[]).length?(transactions??[]).map(t=><div key={t.id} className="credit-request-row"><div><strong>{t.type}</strong><small>{t.description||"Movimento de créditos"} · {new Date(t.created_at).toLocaleString("pt-MZ")}</small></div><strong>{t.credits>0?"+":""}{t.credits.toLocaleString("pt-MZ")} cr</strong></div>):<p className="muted">Ainda não existem movimentos de créditos.</p>}</section>
 </div></main>;
}