export const dynamic="force-dynamic";
import Link from "next/link";import{createClient}from"@/lib/supabase/server";import{PartnerTopbar}from"@/components/partner-workspace";
export default async function PartnerHome(){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)return null;
const[{data:context},{data:opportunities},{data:requests},{data:members},{data:campaigns},{data:entitlements}]=await Promise.all([
s.rpc("partner_account_context"),s.from("opportunities").select("id,title,slug,type,status,organization,location,closes_at,created_at").eq("owner_id",user.id).order("created_at",{ascending:false}).limit(8),
s.from("service_requests").select("id,status,created_at,requested_price,currency,platform_services(name)").eq("requester_user_id",user.id).order("created_at",{ascending:false}).limit(8),
s.rpc("partner_account_members_list"),s.rpc("partner_ad_campaigns_list"),s.rpc("partner_entitlements_list")]);
const name=context?.[0]?.account_name||user.email?.split("@")[0]||"Parceiro";const published=(opportunities??[]).filter(x=>x.status==="PUBLISHED").length;const drafts=(opportunities??[]).filter(x=>x.status==="DRAFT").length;const pending=(requests??[]).filter(x=>["REQUESTED","UNDER_REVIEW","QUOTED"].includes(x.status)).length;const activeCampaigns=(campaigns??[]).filter((x:any)=>["ACTIVE","RUNNING","PUBLISHED"].includes(x.status)).length;const benefits=(entitlements??[]).filter((x:any)=>x.status==="ACTIVE").length;const date=(v:string)=>new Date(v).toLocaleDateString("pt-MZ",{day:"2-digit",month:"short"});
const next=drafts?[{label:"Rever e publicar rascunhos",href:"/parceiro/oportunidades",kind:"ACTIVIDADE"}]:!published?[{label:"Publicar a primeira oportunidade",href:"/parceiro/oportunidades/nova",kind:"ACTIVIDADE"}]:!activeCampaigns?[{label:"Escolher um formato de exposição",href:"/parceiro/publicidade",kind:"EXPOSIÇÃO"}]:[{label:"Explorar inteligência e reputação",href:"/parceiro/servicos",kind:"INTELIGÊNCIA"}];
return <main className="partner-main"><div className="partner-content partner-home"><PartnerTopbar/>
<header className="partner-home-top"><div><span className="partner-kicker">PARTNER COMMAND CENTER</span><h1>{name}</h1><p>Gerir actividade. Comprar exposição. Transformar dados em inteligência.</p></div><div className="partner-home-top-meta"><span>CONTA</span><strong>Activa</strong><small>{members?.length??0} gestor(es) autorizado(s)</small><Link href="/parceiro/conta">Gerir conta →</Link></div></header>
<section className="partner-command-grid"><article className="partner-command-feature"><span className="partner-kicker">ESTADO DA RELAÇÃO</span><strong>Em actividade</strong><p>A sua conta pode publicar oportunidades, activar exposição e solicitar produtos de dados, inteligência e confiança.</p><div><Link href="/parceiro/oportunidades" className="partner-primary-action">Gerir actividade →</Link><Link href="/parceiro/publicidade" className="partner-command-link">Ver exposição</Link></div></article>
<article className="partner-command-action"><span>PRÓXIMA ACÇÃO</span><strong>{next[0].label}</strong><small>{next[0].kind}</small><Link href={next[0].href}>Abrir →</Link></article></section>
<section className="partner-home-metrics"><article><span>Publicações activas</span><strong>{published}</strong><small>{drafts} rascunho(s)</small></article><article><span>Campanhas activas</span><strong>{activeCampaigns}</strong><small>Publicidade e exposição</small></article><article><span>Pedidos em curso</span><strong>{pending}</strong><small>Serviços a acompanhar</small></article><article><span>Benefícios activos</span><strong>{benefits}</strong><small>Exclusividades da conta</small></article></section>
<div className="partner-home-columns"><section className="partner-home-panel"><div className="partner-home-panel-head"><div><span className="partner-kicker">ACTIVIDADE</span><h2>Publicações recentes</h2></div><Link href="/parceiro/oportunidades">Ver todas →</Link></div>{opportunities?.length?<div className="partner-home-list">{opportunities.slice(0,5).map(x=><Link href={"/parceiro/oportunidades/"+x.id} key={x.id}><div><span>{x.status} · {x.type||"OPORTUNIDADE"}</span><strong>{x.title}</strong><small>{x.location||"Localização não indicada"} · {date(x.created_at)}</small></div><b>→</b></Link>)}</div>:<div className="partner-home-empty"><strong>O espaço está pronto para a primeira publicação.</strong><p>Publique uma oportunidade, chamada, financiamento, concurso ou programa.</p><Link href="/parceiro/oportunidades/nova" className="partner-primary-action">Publicar agora →</Link></div>}</section>
<section className="partner-home-panel"><div className="partner-home-panel-head"><div><span className="partner-kicker">VALOR</span><h2>Relação comercial</h2></div><Link href="/parceiro/servicos">Catálogo →</Link></div><div className="partner-value-stack"><Link href="/parceiro/publicidade"><span>01 · EXPOSIÇÃO</span><strong>{activeCampaigns?activeCampaigns+" campanha(s) activa(s)":"Ainda sem campanha activa"}</strong><small>Publicidade, patrocínios e posicionamento perante o público.</small></Link><Link href="/parceiro/servicos"><span>02 · INTELIGÊNCIA</span><strong>{pending?pending+" pedido(s) em curso":"Catálogo disponível para contratação"}</strong><small>Dados, mercado, estudos, reputação e confiança.</small></Link><Link href="/parceiro/resultados"><span>03 · HISTÓRICO</span><strong>Desempenho e registo factual</strong><small>Consulte a actividade e os resultados disponíveis.</small></Link></div></section></div>
<section className="partner-home-panel partner-home-bottom"><div className="partner-home-panel-head"><div><span className="partner-kicker">MODELO MOZEMPRESAS</span><h2>Três formas de criar valor</h2></div></div><div className="partner-value-grid"><article><span>01</span><h3>PUBLICAR</h3><p>A organização coloca oportunidades e actividades diante do mercado.</p><Link href="/parceiro/oportunidades">Gerir actividade →</Link></article><article><span>02</span><h3>POSICIONAR</h3><p>A organização compra exposição, destaque e patrocínio onde o público está.</p><Link href="/parceiro/publicidade">Ver formatos →</Link></article><article><span>03</span><h3>COMPREENDER</h3><p>A organização transforma dados elegíveis em inteligência, confiança e decisões.</p><Link href="/parceiro/servicos">Explorar produtos →</Link></article></div></section>
</div></main>}
