"use client";
import { useMemo, useState } from "react";
type Product={id:string;name:string;placement:string;duration_days:number;direct_price_mzn:number|string;credit_price:number;description?:string|null};
const placementLabel:Record<string,string>={DIRECTORY:"Directório",MARKETPLACE:"Marketplace",HOME:"Página inicial"};
const placementDescription:Record<string,string>={DIRECTORY:"Dê mais visibilidade à sua empresa dentro do Directório.",MARKETPLACE:"Coloque uma oferta em evidência para quem procura produtos e serviços.",HOME:"Ganhe exposição nas áreas de maior visibilidade da página inicial."};
const locationOptions=["Maputo","Matola","Gaza","Inhambane","Sofala","Manica","Tete","Zambézia","Nampula","Cabo Delgado","Niassa"];
function money(v:number|string){return Number(v).toLocaleString("pt-MZ")+" MZN";}
function calculate(p:Product|undefined,l:number,c:number){if(!p)return{price:0,credits:0};const factor=1+(l?0.1:0)+(c?0.1:0);return{price:Number((Number(p.direct_price_mzn)*factor).toFixed(2)),credits:Math.ceil(Number(p.credit_price)*factor)};}
function cleanName(name:string){return name.replace(/\s·\s(7|14|30) dias$/i,"");}
export function AdvertisingPurchaseForm({businesses,products,categories,wallets,creditAction,directAction}:{businesses:{id:string;name:string}[];products:Product[];categories:{name:string}[];wallets:Record<string,number>;creditAction:(f:FormData)=>Promise<void>;directAction:(f:FormData)=>Promise<void>}){
 const placements=["DIRECTORY","MARKETPLACE","HOME"].filter(place=>products.some(p=>p.placement===place));
 const firstPlacement=placements[0]??"DIRECTORY"; const [placement,setPlacement]=useState(firstPlacement);
 const placementProducts=products.filter(p=>p.placement===placement&&Number(p.direct_price_mzn)>0);
 const durations=Array.from(new Set(placementProducts.map(p=>p.duration_days))).sort((a,b)=>a-b);
 const [duration,setDuration]=useState<number>(durations[0]??7); const [productId,setProductId]=useState(placementProducts.find(p=>p.duration_days===duration)?.id??placementProducts[0]?.id??"");
 const [businessId,setBusinessId]=useState(businesses[0]?.id??""); const [locations,setLocations]=useState<string[]>([]); const [cats,setCats]=useState<string[]>([]);
 const options=useMemo(()=>placementProducts.filter(p=>p.duration_days===duration),[placementProducts,duration]); const product=products.find(p=>p.id===productId)??options[0]??placementProducts[0]; const calc=calculate(product,locations.length,cats.length);
 const chooseDuration=(next:number)=>{setDuration(next);const nextProduct=placementProducts.find(p=>p.duration_days===next);if(nextProduct)setProductId(nextProduct.id);};
 const choosePlacement=(next:string)=>{setPlacement(next);const nextProducts=products.filter(p=>p.placement===next&&Number(p.direct_price_mzn)>0);const nextDurations=Array.from(new Set(nextProducts.map(p=>p.duration_days))).sort((a,b)=>a-b);const nextDuration=nextDurations[0]??7;setDuration(nextDuration);setProductId(nextProducts.find(p=>p.duration_days===nextDuration)?.id??"");};
 const toggle=(value:string,setter:(v:string[])=>void,current:string[])=>setter(current.includes(value)?current.filter(x=>x!==value):[...current,value]);
 return <div className="ad-campaign-builder"><div className="ad-builder-progress"><span className="active">01 <b>Campanha</b></span><span>02 <b>Audiência</b></span><span>03 <b>Pagamento</b></span></div><form className="ad-builder-form">
  <section className="ad-builder-section ad-space-selector"><div className="ad-builder-section-head"><span>01</span><div><h3>Escolha onde quer aparecer</h3><p>Primeiro escolha o espaço. Depois escolha a duração e o formato dentro desse espaço.</p></div></div>
   <label className="ad-builder-field"><span>Empresa</span><select name="business_id" value={businessId} onChange={e=>setBusinessId(e.target.value)} required>{businesses.map(b=><option key={b.id} value={b.id}>{b.name} · {wallets[b.id]??0} créditos</option>)}</select></label>
   <input type="hidden" name="ad_product_id" value={productId}/>
   <div className="ad-placement-tabs" role="tablist" aria-label="Espaço publicitário">{placements.map(place=><button type="button" key={place} className={"ad-placement-tab"+(placement===place?" selected":"")} onClick={()=>choosePlacement(place)}><strong>{placementLabel[place]}</strong><span>{placementDescription[place]}</span></button>)}</div>
   <div className="ad-duration-row"><div><span className="ad-builder-label-title">Duração</span><small>Quanto tempo pretende manter a campanha?</small></div><div className="ad-duration-tabs">{durations.map(days=><button type="button" key={days} className={duration===days?"selected":""} onClick={()=>chooseDuration(days)}>{days} dias</button>)}</div></div>
   <div className="ad-format-heading"><div><span className="ad-builder-label-title">Formato dentro de {placementLabel[placement]}</span><small>Escolha uma opção para continuar.</small></div><strong>{duration} dias</strong></div>
   <div className="ad-format-list">{options.map(p=><button type="button" key={p.id} className={"ad-format-option"+(p.id===productId?" selected":"")} onClick={()=>setProductId(p.id)}><span className="ad-format-radio"/><div><strong>{cleanName(p.name)}</strong><small>{p.description}</small></div><div className="ad-format-price"><strong>{money(p.direct_price_mzn)}</strong><small>{Number(p.credit_price).toLocaleString("pt-MZ")} créditos</small></div></button>)}</div>
   <div className="ad-builder-two"><label className="ad-builder-field"><span>Início da campanha</span><input name="starts_at" type="datetime-local" required/></label><label className="ad-builder-field"><span>Nome da campanha <small>(opcional)</small></span><input name="title" placeholder="Ex.: Campanha institucional"/></label></div>
   <label className="ad-builder-field"><span>Oferta associada <small>(opcional)</small></span><input name="listing_id" placeholder="ID da oferta, se aplicável"/></label>
  </section>
  <section className="ad-builder-section"><div className="ad-builder-section-head"><span>02</span><div><h3>Defina a audiência</h3><p>O espaço mantém-se o mesmo; a segmentação acrescenta 10% por tipo de critério.</p></div></div>
   <div className="ad-target-block"><div className="ad-builder-label"><span>Localização <small>+10%</small></span><small>{locations.length?locations.length+" seleccionada(s)":"Opcional"}</small></div><div className="ad-chip-grid">{locationOptions.map(v=><label key={v} className={"ad-chip"+(locations.includes(v)?" selected":"")}><input type="checkbox" name="target_location" value={v} checked={locations.includes(v)} onChange={()=>toggle(v,setLocations,locations)}/>{v}</label>)}</div></div>
   <div className="ad-target-block"><div className="ad-builder-label"><span>Actividade / categoria <small>+10%</small></span><small>{cats.length?cats.length+" seleccionada(s)":"Opcional"}</small></div><div className="ad-chip-grid">{categories.map(c=><label key={c.name} className={"ad-chip"+(cats.includes(c.name)?" selected":"")}><input type="checkbox" name="target_category" value={c.name} checked={cats.includes(c.name)} onChange={()=>toggle(c.name,setCats,cats)}/>{c.name}</label>)}</div></div>
  </section>
  <section className="ad-builder-summary"><div><span className="dashboard-kicker">03 · Resumo</span><h3>{product?cleanName(product.name):"Espaço publicitário"}</h3><p>{duration} dias · {locations.length||cats.length?"Audiência segmentada":"Audiência geral"} · {placementLabel[placement]}</p></div><div className="ad-builder-price"><small>Valor estimado</small><strong>{money(calc.price)}</strong><span>ou {calc.credits.toLocaleString("pt-MZ")} créditos</span></div></section>
  <section className="ad-builder-actions"><div><strong>Como pretende pagar?</strong><p>Use o saldo de créditos ou solicite pagamento directo.</p></div><div className="ad-builder-buttons"><button className="btn primary" type="submit" formAction={creditAction}>Activar com créditos</button><button className="btn" type="submit" formAction={directAction}>Solicitar pagamento directo</button></div></section>
 </form></div>;
}