"use client";
import { useMemo,useState } from "react";
import Link from "next/link";
type Service={id:string;slug:string;name:string;description:string|null;category:string;price:number|string|null;currency:string|null;billing:string|null};
const categoryCopy:Record<string,string>={Presença:"Estruture e fortaleça a forma como a sua empresa aparece na plataforma.",Visibilidade:"Ganhe exposição adicional quando precisa de maior alcance.",Publicidade:"Activa espaços pagos de comunicação dentro do ecossistema.",Contratação:"Apoio da plataforma para encontrar ou avaliar fornecedores.",Inteligência:"Transforme informação empresarial em apoio à decisão."};
function money(s:Service){return s.price==null?"Sob consulta":Number(s.price).toLocaleString("pt-MZ")+" "+(s.currency||"MZN");}
export function PlatformServicesCatalog({services}:{services:Service[]}){const categories=useMemo(()=>Array.from(new Set(services.map(s=>s.category))),[services]);const [category,setCategory]=useState(categories[0]??"");const visible=services.filter(s=>s.category===category);const featured=visible[0];return <section className="services-catalog">
 <div className="service-category-tabs" role="tablist" aria-label="Áreas de serviços">{categories.map(item=><button type="button" key={item} className={category===item?"selected":""} onClick={()=>setCategory(item)}><strong>{item}</strong><span>{services.filter(s=>s.category===item).length} serviços</span></button>)}</div>
 <div className="service-category-intro"><div><span className="dashboard-kicker">Área seleccionada</span><h2>{category}</h2><p>{categoryCopy[category]||"Serviços da plataforma para apoiar operações específicas da sua empresa."}</p></div><span className="service-category-count">{visible.length} opções</span></div>
 {featured?<div className="service-featured"><div><span className="service-featured-label">Serviço em destaque</span><h3>{featured.name}</h3><p>{featured.description}</p></div><div className="service-featured-action"><strong>{money(featured)}</strong><Link href={"/dashboard/servicos/"+featured.slug} className="btn primary">Conhecer e solicitar</Link></div></div>:null}
 <div className="service-option-list">{visible.slice(1).map(service=><article className="service-option-row" key={service.id}><div className="service-option-main"><span className="dashboard-kicker">{service.category}</span><h3>{service.name}</h3><p>{service.description}</p></div><div className="service-option-side"><strong>{money(service)}</strong><Link href={"/dashboard/servicos/"+service.slug} className="text-link">Ver serviço →</Link></div></article>)}</div>
 </section>}