import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

const labels:Record<string,string>={CONTEST:"Concurso",CALL:"Chamada",TENDER:"Contratação",FUNDING:"Financiamento",PARTNERSHIP:"Parceria",TRAINING:"Capacitação",EVENT:"Evento",BUSINESS:"Negócio",OTHER:"Outro"};

export default async function Oportunidades({searchParams}:{searchParams:Promise<{q?:string;type?:string;location?:string}>}) {
  const params=await searchParams;let data:Array<{id:string;title:string;slug:string;type:string;description:string;organization:string|null;location:string|null;closes_at:string|null}>=[];let error=false;
  try{const supabase=await createClient();let query=supabase.from("opportunities").select("id,title,slug,type,description,organization,location,closes_at").eq("status","PUBLISHED").order("created_at",{ascending:false}).limit(48);const q=params.q?.trim();if(q){const safe=q.replace(/[%_,()]/g," ").replace(/\s+/g," ").trim();if(safe)query=query.or(`title.ilike.%${safe}%,description.ilike.%${safe}%,organization.ilike.%${safe}%`);}if(params.type&&params.type!=="all")query=query.eq("type",params.type);if(params.location?.trim())query=query.ilike("location",`%${params.location.trim()}%`);const result=await query;data=result.data??[];error=Boolean(result.error);}catch{error=true;}
  return <main className="page"><div className="container"><section className="page-header"><span className="eyebrow">Oportunidades de negócio</span><h1>Descubra oportunidades para a sua empresa.</h1><p className="muted page-lead">Encontre chamadas, parcerias, financiamento, eventos, necessidades empresariais e outras oportunidades publicadas no mercado.</p></section>
  <form className="toolbar" action="/oportunidades"><input name="q" defaultValue={params.q} placeholder="Pesquisar oportunidade ou organização" /><input name="location" defaultValue={params.location} placeholder="Localização" /><select name="type" defaultValue={params.type||"all"}><option value="all">Todos os tipos</option>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><button className="btn primary">Pesquisar</button></form>
  <section className="section page-section"><div className="section-head"><div><span className="eyebrow">Tipos de oportunidade</span><h2>Explore diferentes formas de negócio</h2></div></div><div className="opportunity-grid">{Object.entries(labels).slice(0,6).map(([v,l])=><Link href={"/oportunidades?type="+v} className="opportunity-card" key={v}><span className="opportunity-label">{l}</span><h3>{l}</h3><p>Ver oportunidades desta categoria publicadas no portal.</p><span className="card-link">Explorar →</span></Link>)}</div></section>
  <div className="result-bar"><strong>{data.length} oportunidades</strong><span>Publicadas</span></div>{error&&<div className="notice">As oportunidades estão temporariamente indisponíveis. Pode continuar a navegar pelo portal.</div>}<div className="grid">{data.map(item=><Link href={"/oportunidades/"+item.slug} className="card listing" key={item.id}><div className="listing-top"><span className="tag">{labels[item.type]||item.type}</span><span className="status-dot">{item.closes_at?`Até ${new Date(item.closes_at).toLocaleDateString("pt-MZ")}`:"Aberta"}</span></div><h3>{item.title}</h3><p>{item.description}</p><div className="meta listing-meta">{item.organization&&<span className="tag">{item.organization}</span>}{item.location&&<span className="tag">{item.location}</span>}</div><span className="card-link">Ver oportunidade →</span></Link>)}{data.length===0&&<div className="empty card"><div className="empty-icon">↗</div><h3>Não existem oportunidades publicadas</h3><p>Quando forem publicadas novas oportunidades, elas aparecerão nesta área.</p><Link href="/registo" className="btn primary">Criar conta empresarial</Link></div></div>
  <section className="request-section page-request"><div className="request-panel"><div><span className="eyebrow inverse-eyebrow">Tem uma necessidade?</span><h2>Publique uma oportunidade para encontrar empresas que possam responder.</h2><p>Use o portal para apresentar uma necessidade, procurar parceiros ou divulgar uma oportunidade empresarial.</p></div><Link href="/dashboard" className="btn light-btn">Publicar oportunidade</Link></div></section></div></main>;
}