create extension if not exists "pgcrypto";
create type public.listing_type as enum ('PRODUCT','SERVICE');
create type public.listing_status as enum ('DRAFT','PUBLISHED','PAUSED','SOLD_OUT','ARCHIVED');
create type public.opportunity_type as enum ('CONTEST','CALL','TENDER','FUNDING','PARTNERSHIP','TRAINING','EVENT','BUSINESS','OTHER');
create type public.opportunity_status as enum ('DRAFT','PUBLISHED','CLOSED','ARCHIVED');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text unique, full_name text, avatar_url text, bio text, location text, website text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.business_categories (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique);
create table public.businesses (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles(id) on delete restrict, name text not null, slug text not null unique, description text, category_id uuid references public.business_categories(id) on delete set null, location text, phone text, email text, website text, logo_url text, cover_url text, is_public boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.business_members (business_id uuid not null references public.businesses(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, role text not null default 'member' check(role in ('owner','admin','member')), created_at timestamptz not null default now(), primary key(business_id,user_id));
create table public.listing_categories (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique);
create table public.listings (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles(id) on delete restrict, business_id uuid references public.businesses(id) on delete set null, title text not null, slug text not null unique, description text not null, category_id uuid references public.listing_categories(id) on delete set null, type public.listing_type not null, price numeric(14,2), currency char(3) not null default 'MZN', status public.listing_status not null default 'DRAFT', location text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.listing_media (id uuid primary key default gen_random_uuid(), listing_id uuid not null references public.listings(id) on delete cascade, storage_path text not null, sort_order integer not null default 0, created_at timestamptz not null default now());
create table public.opportunities (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles(id) on delete restrict, title text not null, slug text not null unique, type public.opportunity_type not null, status public.opportunity_status not null default 'DRAFT', description text not null, organization text, location text, opens_at timestamptz, closes_at timestamptz, requirements text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, type text not null, title text not null, body text, resource_type text, resource_id uuid, read_at timestamptz, created_at timestamptz not null default now());
create table public.audit_logs (id bigint generated always as identity primary key, actor_id uuid references public.profiles(id) on delete set null, action text not null, resource_type text not null, resource_id uuid, before_data jsonb, after_data jsonb, created_at timestamptz not null default now());
create index businesses_category_idx on public.businesses(category_id);
create index businesses_location_idx on public.businesses(location);
create index listings_owner_idx on public.listings(owner_id);
create index listings_status_idx on public.listings(status);
create index listings_type_idx on public.listings(type);
create index opportunities_type_idx on public.opportunities(type);
create index opportunities_status_idx on public.opportunities(status);
alter table public.profiles enable row level security;
alter table public.businesses enable row level security;
alter table public.business_members enable row level security;
alter table public.listings enable row level security;
alter table public.listing_media enable row level security;
alter table public.opportunities enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;
grant select on public.profiles,public.businesses,public.listings,public.opportunities to anon,authenticated;
grant select,insert,update on public.profiles to authenticated;
grant select,insert,update,delete on public.businesses,public.business_members,public.listings,public.listing_media,public.opportunities to authenticated;
grant select,update on public.notifications to authenticated;
create policy "public profiles are readable" on public.profiles for select to anon,authenticated using(true);
create policy "users manage own profile" on public.profiles for all to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);
create policy "public businesses are readable" on public.businesses for select to anon,authenticated using(is_public=true or owner_id=(select auth.uid()));
create policy "owners manage businesses" on public.businesses for all to authenticated using(owner_id=(select auth.uid())) with check(owner_id=(select auth.uid()));
create policy "members can view membership" on public.business_members for select to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid())));
create policy "owners manage membership" on public.business_members for all to authenticated using(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid()))) with check(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid())));
create policy "published listings are readable" on public.listings for select to anon,authenticated using(status='PUBLISHED' or owner_id=(select auth.uid()));
create policy "owners manage listings" on public.listings for all to authenticated using(owner_id=(select auth.uid())) with check(owner_id=(select auth.uid()));
create policy "listing media readable" on public.listing_media for select to anon,authenticated using(exists(select 1 from public.listings l where l.id=listing_id and (l.status='PUBLISHED' or l.owner_id=(select auth.uid()))));
create policy "listing owners manage media" on public.listing_media for all to authenticated using(exists(select 1 from public.listings l where l.id=listing_id and l.owner_id=(select auth.uid()))) with check(exists(select 1 from public.listings l where l.id=listing_id and l.owner_id=(select auth.uid())));
create policy "published opportunities readable" on public.opportunities for select to anon,authenticated using(status='PUBLISHED' or owner_id=(select auth.uid()));
create policy "owners manage opportunities" on public.opportunities for all to authenticated using(owner_id=(select auth.uid())) with check(owner_id=(select auth.uid()));
create policy "users read own notifications" on public.notifications for select to authenticated using(user_id=(select auth.uid()));
create policy "users update own notifications" on public.notifications for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy "audit logs not client writable" on public.audit_logs for select to authenticated using(actor_id=(select auth.uid()));