create type public.order_status as enum ('PENDING','CONFIRMED','PROCESSING','COMPLETED','CANCELLED');
create type public.payment_status as enum ('PENDING','AUTHORIZED','PAID','FAILED','REFUNDED');
create type public.contest_status as enum ('DRAFT','PUBLISHED','OPEN','CLOSED','EVALUATION','RESULTS','ARCHIVED');
create type public.repository_item_type as enum ('DOCUMENT','GUIDE','TEMPLATE','REPORT','PUBLICATION','RESOURCE','OTHER');

create table public.carts (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references public.profiles(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.cart_items (id uuid primary key default gen_random_uuid(), cart_id uuid not null references public.carts(id) on delete cascade, listing_id uuid not null references public.listings(id) on delete restrict, quantity integer not null default 1 check(quantity>0), created_at timestamptz not null default now(), unique(cart_id,listing_id));
create table public.orders (id uuid primary key default gen_random_uuid(), buyer_id uuid not null references public.profiles(id) on delete restrict, status public.order_status not null default 'PENDING', currency char(3) not null default 'MZN', subtotal numeric(14,2) not null default 0, total numeric(14,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, listing_id uuid not null references public.listings(id) on delete restrict, seller_id uuid not null references public.profiles(id) on delete restrict, title_snapshot text not null, unit_price numeric(14,2) not null default 0, quantity integer not null default 1 check(quantity>0), total numeric(14,2) not null default 0);
create table public.payments (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete restrict, provider text not null, provider_reference text, amount numeric(14,2) not null, currency char(3) not null default 'MZN', status public.payment_status not null default 'PENDING', metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.payment_events (id uuid primary key default gen_random_uuid(), payment_id uuid not null references public.payments(id) on delete cascade, event_type text not null, provider_event_id text, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create table public.contests (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles(id) on delete restrict, business_id uuid references public.businesses(id) on delete set null, title text not null, slug text not null unique, description text not null, status public.contest_status not null default 'DRAFT', category text, rules text, opens_at timestamptz, closes_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.contest_requirements (id uuid primary key default gen_random_uuid(), contest_id uuid not null references public.contests(id) on delete cascade, title text not null, description text, required boolean not null default true);
create table public.contest_questions (id uuid primary key default gen_random_uuid(), contest_id uuid not null references public.contests(id) on delete cascade, question text not null, question_type text not null default 'TEXT', sort_order integer not null default 0, required boolean not null default true);
create table public.contest_applications (id uuid primary key default gen_random_uuid(), contest_id uuid not null references public.contests(id) on delete cascade, applicant_id uuid not null references public.profiles(id) on delete restrict, status text not null default 'SUBMITTED', submitted_at timestamptz not null default now(), unique(contest_id,applicant_id));
create table public.application_answers (id uuid primary key default gen_random_uuid(), application_id uuid not null references public.contest_applications(id) on delete cascade, question_id uuid not null references public.contest_questions(id) on delete cascade, answer text);
create table public.application_documents (id uuid primary key default gen_random_uuid(), application_id uuid not null references public.contest_applications(id) on delete cascade, storage_path text not null, file_name text not null, created_at timestamptz not null default now());
create table public.evaluation_criteria (id uuid primary key default gen_random_uuid(), contest_id uuid not null references public.contests(id) on delete cascade, name text not null, description text, weight numeric(8,3) not null default 1, max_score numeric(8,2) not null default 100);
create table public.contest_evaluations (id uuid primary key default gen_random_uuid(), application_id uuid not null references public.contest_applications(id) on delete cascade, evaluator_id uuid not null references public.profiles(id) on delete restrict, criterion_id uuid not null references public.evaluation_criteria(id) on delete cascade, score numeric(8,2) not null default 0, comments text, created_at timestamptz not null default now());
create table public.contest_results (id uuid primary key default gen_random_uuid(), application_id uuid not null unique references public.contest_applications(id) on delete cascade, rank integer, final_score numeric(10,2), result text not null default 'PENDING', published_at timestamptz);

create table public.opportunity_applications (id uuid primary key default gen_random_uuid(), opportunity_id uuid not null references public.opportunities(id) on delete cascade, applicant_id uuid not null references public.profiles(id) on delete restrict, status text not null default 'SUBMITTED', submitted_at timestamptz not null default now(), unique(opportunity_id,applicant_id));

create table public.repository_categories (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique);
create table public.repository_items (id uuid primary key default gen_random_uuid(), owner_id uuid references public.profiles(id) on delete set null, category_id uuid references public.repository_categories(id) on delete set null, title text not null, slug text not null unique, description text, item_type public.repository_item_type not null, is_public boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.repository_files (id uuid primary key default gen_random_uuid(), item_id uuid not null references public.repository_items(id) on delete cascade, storage_path text not null, file_name text not null, mime_type text, size_bytes bigint, created_at timestamptz not null default now());
create table public.repository_tags (item_id uuid not null references public.repository_items(id) on delete cascade, tag text not null, primary key(item_id,tag));

create table public.favorites (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, resource_type text not null, resource_id uuid not null, created_at timestamptz not null default now(), unique(user_id,resource_type,resource_id));
create table public.follows (id uuid primary key default gen_random_uuid(), follower_id uuid not null references public.profiles(id) on delete cascade, resource_type text not null, resource_id uuid not null, created_at timestamptz not null default now(), unique(follower_id,resource_type,resource_id));
create table public.reviews (id uuid primary key default gen_random_uuid(), author_id uuid not null references public.profiles(id) on delete restrict, resource_type text not null, resource_id uuid not null, rating integer not null check(rating between 1 and 5), body text, created_at timestamptz not null default now());
create table public.reports (id uuid primary key default gen_random_uuid(), reporter_id uuid not null references public.profiles(id) on delete restrict, resource_type text not null, resource_id uuid not null, reason text not null, details text, status text not null default 'OPEN', created_at timestamptz not null default now());
create table public.views (id bigint generated always as identity primary key, user_id uuid references public.profiles(id) on delete set null, resource_type text not null, resource_id uuid not null, created_at timestamptz not null default now());

create table public.plans (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique, description text, price numeric(14,2) not null default 0, currency char(3) not null default 'MZN', billing_period text not null default 'MONTHLY', active boolean not null default true);
create table public.features (id uuid primary key default gen_random_uuid(), key text not null unique, name text not null, description text);
create table public.subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, plan_id uuid not null references public.plans(id) on delete restrict, status text not null default 'ACTIVE', starts_at timestamptz not null default now(), ends_at timestamptz);
create table public.entitlements (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, feature_id uuid not null references public.features(id) on delete cascade, quantity integer, expires_at timestamptz, unique(user_id,feature_id));
create table public.upsell_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, feature_id uuid references public.features(id) on delete set null, source text, created_at timestamptz not null default now());

alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;
alter table public.payment_events enable row level security;
alter table public.contests enable row level security;
alter table public.contest_requirements enable row level security;
alter table public.contest_questions enable row level security;
alter table public.contest_applications enable row level security;
alter table public.application_answers enable row level security;
alter table public.application_documents enable row level security;
alter table public.evaluation_criteria enable row level security;
alter table public.contest_evaluations enable row level security;
alter table public.contest_results enable row level security;
alter table public.opportunity_applications enable row level security;
alter table public.repository_items enable row level security;
alter table public.repository_files enable row level security;
alter table public.repository_tags enable row level security;
alter table public.favorites enable row level security;
alter table public.follows enable row level security;
alter table public.reviews enable row level security;
alter table public.reports enable row level security;
alter table public.views enable row level security;
alter table public.plans enable row level security;
alter table public.features enable row level security;
alter table public.subscriptions enable row level security;
alter table public.entitlements enable row level security;
alter table public.upsell_events enable row level security;

grant select,insert,update,delete on public.carts,public.cart_items to authenticated;
grant select,insert on public.orders,public.order_items to authenticated;
grant select on public.payments to authenticated;
grant select,insert,update,delete on public.contests,public.contest_requirements,public.contest_questions,public.contest_applications,public.application_answers,public.application_documents,public.evaluation_criteria,public.contest_evaluations,public.contest_results to authenticated;
grant select,insert on public.opportunity_applications to authenticated;
grant select on public.repository_items,public.repository_files,public.repository_tags,public.plans,public.features to anon,authenticated;
grant select,insert,delete on public.favorites,public.follows to authenticated;
grant select,insert on public.reviews,public.reports,public.views to authenticated;
grant select on public.subscriptions,public.entitlements to authenticated;
grant insert on public.upsell_events to authenticated;

create policy "users manage carts" on public.carts for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy "users manage cart items" on public.cart_items for all to authenticated using(exists(select 1 from public.carts c where c.id=cart_id and c.user_id=(select auth.uid()))) with check(exists(select 1 from public.carts c where c.id=cart_id and c.user_id=(select auth.uid())));
create policy "buyers view orders" on public.orders for select to authenticated using(buyer_id=(select auth.uid()));
create policy "buyers create orders" on public.orders for insert to authenticated with check(buyer_id=(select auth.uid()));
create policy "order items visible to buyers" on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and o.buyer_id=(select auth.uid())) or seller_id=(select auth.uid()));
create policy "payments visible to buyers" on public.payments for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and o.buyer_id=(select auth.uid())));
create policy "contest owners manage" on public.contests for all to authenticated using(owner_id=(select auth.uid())) with check(owner_id=(select auth.uid()));
create policy "published contests readable" on public.contests for select to anon,authenticated using(status in ('PUBLISHED','OPEN','CLOSED','EVALUATION','RESULTS') or owner_id=(select auth.uid()));
create policy "contest requirements readable" on public.contest_requirements for select to anon,authenticated using(exists(select 1 from public.contests c where c.id=contest_id and (c.status <> 'DRAFT' or c.owner_id=(select auth.uid()))));
create policy "contest owners manage requirements" on public.contest_requirements for all to authenticated using(exists(select 1 from public.contests c where c.id=contest_id and c.owner_id=(select auth.uid()))) with check(exists(select 1 from public.contests c where c.id=contest_id and c.owner_id=(select auth.uid())));
create policy "contest owners manage questions" on public.contest_questions for all to authenticated using(exists(select 1 from public.contests c where c.id=contest_id and c.owner_id=(select auth.uid()))) with check(exists(select 1 from public.contests c where c.id=contest_id and c.owner_id=(select auth.uid())));
create policy "applicants manage own applications" on public.contest_applications for all to authenticated using(applicant_id=(select auth.uid())) with check(applicant_id=(select auth.uid()));
create policy "contest owners read applications" on public.contest_applications for select to authenticated using(exists(select 1 from public.contests c where c.id=contest_id and c.owner_id=(select auth.uid())));
create policy "applicants manage answers" on public.application_answers for all to authenticated using(exists(select 1 from public.contest_applications a where a.id=application_id and a.applicant_id=(select auth.uid()))) with check(exists(select 1 from public.contest_applications a where a.id=application_id and a.applicant_id=(select auth.uid())));
create policy "applicants manage documents" on public.application_documents for all to authenticated using(exists(select 1 from public.contest_applications a where a.id=application_id and a.applicant_id=(select auth.uid()))) with check(exists(select 1 from public.contest_applications a where a.id=application_id and a.applicant_id=(select auth.uid())));
create policy "public repository readable" on public.repository_items for select to anon,authenticated using(is_public=true or owner_id=(select auth.uid()));
create policy "owners manage repository items" on public.repository_items for all to authenticated using(owner_id=(select auth.uid())) with check(owner_id=(select auth.uid()));
create policy "repository files readable" on public.repository_files for select to anon,authenticated using(exists(select 1 from public.repository_items r where r.id=item_id and (r.is_public=true or r.owner_id=(select auth.uid()))));
create policy "repository owners manage files" on public.repository_files for all to authenticated using(exists(select 1 from public.repository_items r where r.id=item_id and r.owner_id=(select auth.uid()))) with check(exists(select 1 from public.repository_items r where r.id=item_id and r.owner_id=(select auth.uid())));
create policy "users manage favorites" on public.favorites for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy "users manage follows" on public.follows for all to authenticated using(follower_id=(select auth.uid())) with check(follower_id=(select auth.uid()));
create policy "reviews readable" on public.reviews for select to anon,authenticated using(true);
create policy "users create reviews" on public.reviews for insert to authenticated with check(author_id=(select auth.uid()));
create policy "users manage reports" on public.reports for all to authenticated using(reporter_id=(select auth.uid())) with check(reporter_id=(select auth.uid()));
create policy "views readable" on public.views for select to authenticated using(user_id=(select auth.uid()));
create policy "users view own subscriptions" on public.subscriptions for select to authenticated using(user_id=(select auth.uid()));
create policy "users view own entitlements" on public.entitlements for select to authenticated using(user_id=(select auth.uid()));
create policy "users create upsell events" on public.upsell_events for insert to authenticated with check(user_id=(select auth.uid()));