export const dynamic="force-dynamic";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
const money=(v:number|string|null|undefined)=>v==null?"—":Number(v).toLocaleString("pt-MZ",{minimumFractionDigits:2,maximumFractionDigits:2})+" MZN";
const method=(v:string|null)=>v==="MPESA"?"M-Pesa":v==="BANK_TRANSFER"?"Transferência bancária":v==="CREDITS"?"Créditos":v||"—";
const status=(v:string)=>v==="PAID"||v==="CONFIRMED"?"Pago":v==="PENDING"||v==="PENDING_PAYMENT"?"Pendente":v==="COMPLETED"?"Concluído":v==="IN_PROGRESS"?"Em execução":v==="FAILED"?"Falhou":v==="REFUNDED"?"Reembolsado":v==="CANCELLED"?"Cancelado":v;
export default async function FinancePage(){
 const s=await createClient(); const {data:{user}}=await s.auth.getUser(); if(!user)redirect("/login");
 const [{data:owned},{data:members}]=await Promise.all([s.from("businesses").select("id,name").eq("owner_id",user.id).order("name"),s.from("business_members").select("business_id").eq("user_id",user.id).in("role",["owner","admin","operator"])]);
 const ids=[...new Set((members??[]).map(x=>x.business_id))]; const {data:managed}=ids.length?await s.from("businesses").select("id,name").in("id",ids).order("name"):{data:[] as {id:string;name:string}[]};
 const businesses=[...(owned??[]),...(managed??[]).filter(b=>!(owned??[]).some(o=>o.id===b.id))]; const bid=businesses.map(b=>b.id);
 const [{data:payments},{data:docs},{data:orders},{data:wallets},{data:creditRequests}]=await Promise.all([
  bid.length?s.from("financial_payments").select("id,business_id,amount_mzn,method,status,reference,created_at").in("business_id",bid).order("created_at",{ascending:false}).limit(30):Promise.resolve({data:[]}),
  bid.length?s.from("financial_documents").select("id,business_id,document_type,document_number,status,amount_mzn,issued_at").in("business_id",bid).order("issued_at",{ascending:false}).limit(30):Promise.resolve({data:[]}),
  bid.length?s.from("platform_service_orders").select("id,business_id,service_id,amount_mzn,payment_method,status,credits_charged,created_at").in("business_id",bid).order("created_at",{ascending:false}).limit(20):Promise.resolve({data:[]}),
  bid.length?s.from("business_credit_wallets").select("business_id,balance_credits").in("business_id",bid):Promise.resolve({data:[]}),
  bid.length?s.from("credit_purchase_requests").select("id,business_id,credits,amount_mzn,payment_method,status,created_at").in("business_id",bid).order("created_at",{ascending:false}).limit(15):Promise.resolve({data:[]})
 ]);
 const paid=(payments??[]).filter(p=>p.status==="CONFIRMED").reduce((n,p)=>n+Number(p.amount_mzn),0); const pending=(payments??[]).filter(p=>p.status==="PENDING").reduce((n,p)=>n+Number(p.amount_mzn),0); const credits=(wallets??[]).reduce((n,w)=>n+Number(w.balance_credits),0);
 return <main className="dashboard-main"><div className="dashboard-content">
  <header className="dashboard-topbar finance-hero"><div><span className="dashboard-kicker">Conta · Gestão financeira</span><h1>Gestão financeira</h1><p>Controle pagamentos, facturas, compras de serviços e créditos das empresas que representa.</p></div><Link href="/dashboard/monetizacao/creditos" className="btn primary">Comprar créditos →</Link></header>
  <section className="finance-metrics responsive-state-block"><div><span>Pagamentos confirmados</span><strong>{money(paid)}</strong></div><div><span>Pagamentos pendentes</span><strong>{money(pending)}</strong></div><div><span>Saldo de créditos</span><strong>{credits.toLocaleString("pt-MZ")} cr</strong></div><div><span>Empresas sob gestão</span><strong>{businesses.length}</strong></div></section>
  <section className="dashboard-section finance-section"><div className="dashboard-section-head"><div><span className="dashboard-kicker">Movimentos</span><h2>Histórico de pagamentos</h2><p className="muted">M-Pesa, transferências e pagamentos efectuados com créditos.</p></div></div>{(payments??[]).length?(payments??[]).map(p=><div className="finance-row" key={p.id}><div><strong>{businesses.find(b=>b.id===p.business_id)?.name||"Empresa"}</strong><small>{method(p.method)}{p.reference?" · "+p.reference:""} · {new Date(p.created_at).toLocaleString("pt-MZ")}</small></div><div><strong>{money(p.amount_mzn)}</strong><span>{status(p.status)}</span></div></div>):<p className="muted">Ainda não existem pagamentos registados.</p>}</section>
  <section className="finance-two-col"><section className="dashboard-section finance-section"><div className="dashboard-section-head"><div><span className="dashboard-kicker">Documentos</span><h2>Facturas e documentos</h2></div></div>{(docs??[]).length?(docs??[]).map(d=><div className="finance-row" key={d.id}><div><strong>{d.document_number}</strong><small>{d.document_type.replaceAll("_"," ")} · {new Date(d.issued_at).toLocaleDateString("pt-MZ")}</small></div><div><strong>{money(d.amount_mzn)}</strong><span>{status(d.status)}</span></div></div>):<p className="muted">Ainda não existem documentos financeiros.</p>}</section>
  <section className="dashboard-section finance-section"><div className="dashboard-section-head"><div><span className="dashboard-kicker">Serviços</span><h2>Serviços adquiridos</h2></div></div>{(orders??[]).length?(orders??[]).map(o=><div className="finance-row" key={o.id}><div><strong>Serviço MozEmpresas</strong><small>{method(o.payment_method)} · {new Date(o.created_at).toLocaleDateString("pt-MZ")}</small></div><div><strong>{money(o.amount_mzn)}</strong><span>{status(o.status)}</span></div></div>):<p className="muted">Ainda não existem serviços adquiridos.</p>}</section></section>
  <section className="dashboard-section finance-section"><div className="dashboard-section-head"><div><span className="dashboard-kicker">Créditos</span><h2>Compras de créditos</h2><p className="muted">Compras por M-Pesa ou transferência bancária com comprovativo.</p></div></div>{(creditRequests??[]).length?(creditRequests??[]).map(r=><div className="finance-row" key={r.id}><div><strong>{r.credits.toLocaleString("pt-MZ")} créditos · {businesses.find(b=>b.id===r.business_id)?.name||"Empresa"}</strong><small>{method(r.payment_method)} · {new Date(r.created_at).toLocaleString("pt-MZ")}</small></div><div><strong>{money(r.amount_mzn)}</strong><span>{status(r.status)}</span></div></div>):<p className="muted">Ainda não existem compras de créditos.</p>}</section>
 </div></main>;
}